const envFlag = String(import.meta.env.VITE_DEBUG_MODE || '').toLowerCase();

export const DEBUG_MODE = envFlag === 'true' || envFlag === '1';

export const DEBUG_FORM_DATA = {
  loginByType: {
    user: {
      email: 'juan.perez@example.com',
      password: 'debug123',
    },
    company: {
      email: 'empresa.debug@example.com',
      password: 'company123',
    },
    admin: {
      email: 'admin@jobplatform.com',
      password: 'admin123',
    },
    psychologist: {
      email: 'psicologa.debug@example.com',
      password: 'debug123',
    },
    patient: {
      email: 'paciente.debug@example.com',
      password: 'debug123',
    },
  },
  registerUser: {
    firstName: 'Juan',
    lastName: 'Perez',
    email: 'juan.perez@example.com',
    password: 'debug123',
    confirmPassword: 'debug123',
    phone: '+54 11 1234 5678',
    cv: null,
  },
  registerCompany: {
    companyName: 'Empresa Debug SA',
    email: 'empresa.debug@example.com',
    password: 'company123',
    confirmPassword: 'company123',
    website: 'https://empresa-debug.com',
    industry: 'Tecnologia',
    size: '51-200',
    location: 'Buenos Aires',
    description: 'Empresa de prueba para modo debug.',
    logo: null,
  },
  createJob: {
    title: 'Desarrollador Frontend React',
    description: 'Buscamos frontend developer con experiencia en React y testing.',
    location: 'Capital Federal',
    categoryId: '',
    postingLanguage: 'es',
    requirementsText: 'React\nJavaScript\nGit',
    responsibilitiesText: 'Desarrollar features\nMantener codigo\nCode reviews',
    languagesText: 'Espanol, Ingles',
    salaryMin: '1200000',
    salaryMax: '1800000',
    salaryPeriod: 'monthly',
    workType: 'FULL_TIME',
    workMode: 'REMOTO',
    experienceLevel: 'MID',
    whatsappNumber: '+54 11 5555 5555',
    contactEmail: 'rrhh@empresa-debug.com',
    expiresAt: '2026-12-31',
  },
  registerPatient: {
    firstName: 'Carlos',
    lastName: 'Lopez',
    email: 'paciente.debug@example.com',
    password: 'debug123',
    confirmPassword: 'debug123',
    gender: 'Hombre',
  },
  registerPsychologistAR: {
    email: 'psicologa.ar.debug@example.com',
    password: 'debug123',
    confirmPassword: 'debug123',
    firstName: 'Lucia',
    lastName: 'Fernandez',
    gender: 'Mujer',
    dateOfBirth: '1988-04-15',
    phone: '+54 9 11 5555 1111',
    contactEmail: 'lucia.fernandez.consultorio@example.com',
    dni: '30111222',
    cuitCuil: '27-30111222-5',
    addressStreet: 'Av. Santa Fe',
    addressNumber: '2450',
    addressFloor: '6 B',
    addressCity: 'Buenos Aires',
    addressProvince: 'Ciudad de Buenos Aires',
    addressPostalCode: 'C1425',
    practiceProvince: 'Ciudad de Buenos Aires',
    universityDegree: 'Lic. en Psicología',
    graduationYear: '2014',
    universityName: 'Universidad de Buenos Aires',
    licenseNumber: 'MP 45821',
    licenseProvince: 'Ciudad de Buenos Aires',
    healthMinistryReg: 'MSAL-AR-8821',
    virtualConsultingAuthorization: 'Habilitación especial de consultorio virtual',
    sessionCost: 'ARS 25.000',
    sessionDuration: '50 minutos',
    yearsExperience: '9',
    remoteModality: 'Telepsicología / Telemedicina',
    bio: 'Psicóloga clínica con experiencia en atención online de adultos y parejas.',
    languages: ['Español', 'Inglés'],
    specialties: ['Psicología clínica y de la salud', 'Terapia de pareja y familiar'],
    ageRanges: ['Adultos (mayor a 18 años)'],
  },
  registerPsychologistINTL: {
    email: 'psychologist.intl.debug@example.com',
    password: 'debug123',
    confirmPassword: 'debug123',
    firstName: 'Sofia',
    lastName: 'Martins',
    gender: 'Mujer',
    dateOfBirth: '1986-09-22',
    phone: '+351 912 000 111',
    contactEmail: 'sofia.martins.practice@example.com',
    documentType: 'Pasaporte',
    documentNumber: 'XP1234567',
    taxId: 'PT-99887766',
    country: 'Portugal',
    region: 'Lisboa',
    addressStreet: 'Rua Augusta',
    addressNumber: '120',
    addressFloor: '3',
    addressCity: 'Lisboa',
    addressPostalCode: '1100-053',
    universityDegree: 'Lic. en Psicología',
    licenseNumber: 'OM-PSI-7788',
    licenseEntity: 'Ordem dos Psicólogos Portugueses',
    licenseCountry: 'Portugal',
    degreeInstitution: 'Universidade de Lisboa',
    sessionCost: 'EUR 40',
    sessionDuration: '50 minutos',
    yearsExperience: '11',
    remoteModality: 'Telepsicología / Telemedicina',
    bio: 'Psicóloga con experiencia en terapia online para adultos, ansiedad y procesos migratorios.',
    languages: ['Español', 'Portugués', 'Inglés'],
    specialties: ['Psicología clínica y de la salud', 'Psicología social y comunitaria'],
    ageRanges: ['Adultos (mayor a 18 años)', 'Infanto-juvenil (hasta los 18 años)'],
  },
};

export const getDebugLoginData = (userType = 'user') =>
  DEBUG_FORM_DATA.loginByType[userType] || DEBUG_FORM_DATA.loginByType.user;
