const DEFAULT_CATEGORIES = [
  { name: 'Moderador de Comunidades (Discord/Telegram)', slug: 'moderador-comunidades-discord-telegram', description: 'Gestión y moderación de comunidades online.' },
  { name: 'Tutor/Profesor Online primaria, secundaria', slug: 'tutor-profesor-online-primaria-secundaria', description: 'Docencia online para niveles primaria y secundaria.' },
  { name: 'Tutor/Profesor Online universidad, terciario', slug: 'tutor-profesor-online-universidad-terciario', description: 'Docencia online para nivel universitario y terciario.' },
  { name: 'Curador de Contenido para Redes Sociales', slug: 'curador-contenido-redes-sociales', description: 'Selección y organización de contenido para redes sociales.' },
  { name: 'Ingeniero de Prompts (Prompt Engineer) IA', slug: 'ingeniero-prompts-ia', description: 'Diseño y optimización de prompts para sistemas de IA.' },
  { name: 'Revisor de Contenido Escolar (Gaggle)', slug: 'revisor-contenido-escolar-gaggle', description: 'Revisión y monitoreo de contenido escolar digital.' },
  { name: 'Probador de Usabilidad (UserTesting)', slug: 'probador-usabilidad-usertesting', description: 'Pruebas de experiencia de usuario y usabilidad.' },
  { name: 'Especialista en Finanzas/Contabilidad', slug: 'especialista-finanzas-contabilidad', description: 'Gestión financiera, contable y análisis económico.' },
  { name: 'Etiquetador de Datos para IA', slug: 'etiquetador-datos-ia', description: 'Etiquetado y clasificación de datos para modelos de IA.' },
  { name: 'Transcriptor de Reuniones Online', slug: 'transcriptor-reuniones-online', description: 'Transcripción de reuniones virtuales y contenido audiovisual.' },
  { name: 'Dibujante Comic / Manga / etc.', slug: 'dibujante-comic-manga', description: 'Ilustración y diseño de arte secuencial.' },
  { name: 'BI, Especialista en Ciberseguridad', slug: 'bi-especialista-ciberseguridad', description: 'Análisis de negocio y seguridad informática.' },
  { name: 'Experto/a en Cloud (AWS, Azure)', slug: 'experto-cloud-aws-azure', description: 'Arquitectura, despliegue y operación de soluciones cloud.' },
  { name: 'Especialista en Marketing Digital', slug: 'especialista-marketing-digital', description: 'Estrategias digitales de adquisición y crecimiento.' },
  { name: 'Especialista en Atención al Cliente', slug: 'especialista-atencion-cliente', description: 'Soporte y gestión de experiencia de cliente.' },
  { name: 'Creador de Productos Digitales', slug: 'creador-productos-digitales', description: 'Diseño y desarrollo de productos digitales.' },
  { name: 'Telemedicina', slug: 'especialista-telemedicina', description: 'Servicios y operación en salud digital a distancia.' },
  { name: 'Consultor de Sostenibilidad', slug: 'consultor-sostenibilidad', description: 'Asesoría en prácticas ambientales y sostenibles.' },
  { name: 'Investigación de mercados', slug: 'investigacion-mercados', description: 'Estudio de mercado, audiencias y competencia.' },
  { name: 'Diseñador Indumentaria', slug: 'disenador-indumentaria', description: 'Diseño y desarrollo de colecciones de indumentaria.' },
  { name: 'Ingeniero/a de Software', slug: 'ingeniero-software', description: 'Desarrollo y arquitectura de software.' },
  { name: 'Redactor/a de Contenidos', slug: 'redactor-contenidos', description: 'Creación de contenidos escritos para distintos canales.' },
  { name: 'Social Media Manager', slug: 'social-media-manager', description: 'Planificación y gestión integral de redes sociales.' },
  { name: 'Profesores de Idiomas', slug: 'profesores-idiomas', description: 'Enseñanza de idiomas en distintos niveles.' },
  { name: 'Copywriter (con SEO)', slug: 'copywriter-seo', description: 'Redacción persuasiva optimizada para buscadores.' },
  { name: 'Ejecutivo/a de Ventas', slug: 'ejecutivo-ventas', description: 'Gestión comercial y cierre de oportunidades.' },
  { name: 'Marketing digital', slug: 'marketing-digital', description: 'Campañas y acciones de marketing en canales digitales.' },
  { name: 'Escritor / Guionista', slug: 'escritor-guionista', description: 'Escritura creativa y desarrollo de guiones.' },
  { name: 'Profesor Secundaria', slug: 'profesor-secundaria', description: 'Docencia para nivel secundario.' },
  { name: 'Diseñador Gráfico', slug: 'disenador-grafico', description: 'Comunicación visual y diseño gráfico.' },
  { name: 'Profesor Primaria', slug: 'profesor-primaria', description: 'Docencia para nivel primario.' },
  { name: 'Ingeniero/a de IA', slug: 'ingeniero-ia', description: 'Desarrollo e implementación de soluciones de inteligencia artificial.' },
  { name: 'Analista de Datos', slug: 'analista-datos', description: 'Análisis, modelado y visualización de datos.' },
  { name: 'Project Manager', slug: 'project-manager', description: 'Gestión de proyectos y coordinación de equipos.' },
  { name: 'Product Manager', slug: 'product-manager', description: 'Definición y estrategia de producto digital.' },
  { name: 'Arquitecto', slug: 'arquitecto', description: 'Diseño y planificación arquitectónica.' },
  { name: 'Publicidad', slug: 'publicidad', description: 'Estrategias y producción publicitaria.' },
  { name: 'Márquetin', slug: 'marquetin', description: 'Planificación y ejecución de acciones de márquetin.' },
  { name: 'Traductor', slug: 'traductor', description: 'Traducción de documentos y contenidos.' },
  { name: 'Redactor', slug: 'redactor', description: 'Redacción general de textos.' },
  { name: 'Fotógrafo', slug: 'fotografo', description: 'Producción y edición fotográfica.' },
  { name: 'Abogado', slug: 'abogado', description: 'Asesoramiento y gestión legal.' },
  { name: 'Finanzas', slug: 'finanzas', description: 'Gestión económica y financiera.' },
  { name: 'Casting', slug: 'casting', description: 'Selección de perfiles para producciones y eventos.' },
  { name: 'Otros', slug: 'otros', description: 'Categorías generales o no listadas.' },
];

module.exports = { DEFAULT_CATEGORIES };
